ports:
  - name: Anythink Frontend
    description: The frontend react app for Anythink
    port: 3001
    onOpen: open-preview
  - name: Anythink Backend 
    description: The backend app for Anythink
    port: 3000
    visibility: public
    onOpen: ignore
  - name: Postgres Database
    description: The DB for Anythink
    port: 5433
    onOpen: ignore

tasks:
  - name: Docker
    command: docker-compose up && gp sync-done docker
    openMode: split-left
  - name: Seed Database 
    before: gp sync-await docker # wait for the above 'docker' to finish
    init: sh ./backend/seeds.sh
    command: echo 'ALL DONE! Enjoy :)'
    openMode: split-right