ports:
  - name: Anythink Frontend
    description: The frontend react app for Anythink
    port: 3001
    onOpen: open-preview
  - name: Anythink Backend 
    description: The backend app for Anythink
    port: 3000
    visibility: public
    onOpen: ignore
  - name: Postgres Database
    description: The DB for Anythink
    port: 5433
    onOpen: ignore

tasks:
  - name: Dockers
    command: docker-compose up && gp sync-done docker
    openMode: split-right
  - name: Run migrations & Seed Database
    init: echo "Waiting for docker to finish..." && gp sync-await docker
    command: >
      docker exec -it anythink-backend bash -c "cd backend && rails db:migrate" &&
      docker exec -it anythink-backend bash -c "cd backend && ./seeds.sh" &&
      echo "ALL DONE! :) Enjoy."
    openMode: split-left